const STATUS = {
  ENTRY_PLACED: "ENTRY_PLACED",
  ENTRY_OPEN: "ENTRY_OPEN",
  ENTRY_REPLACED: "ENTRY_REPLACED",
  ENTRY_CANCELLED: "ENTRY_CANCELLED",
  ENTRY_FILLED: "ENTRY_FILLED",
  LIVE: "LIVE",
  SL_PLACED: "SL_PLACED",
  SL_OPEN: "SL_OPEN",
  SL_CONFIRMED: "SL_CONFIRMED",
  EXIT_PLACED: "EXIT_PLACED",
  EXIT_OPEN: "EXIT_OPEN",
  EXIT_PARTIAL: "EXIT_PARTIAL",
  EXIT_FILLED: "EXIT_FILLED",
  PANIC_EXIT_PLACED: "PANIC_EXIT_PLACED",
  PANIC_EXIT_CONFIRMED: "PANIC_EXIT_CONFIRMED",
  RECOVERY_REHYDRATED: "RECOVERY_REHYDRATED",
  EXITED_TARGET: "EXITED_TARGET",
  EXITED_SL: "EXITED_SL",
  ENTRY_FAILED: "ENTRY_FAILED",
  GUARD_FAILED: "GUARD_FAILED",
  CLOSED: "CLOSED",
};

const ALLOWED_TRANSITIONS = {
  [STATUS.ENTRY_PLACED]: new Set([
    STATUS.ENTRY_OPEN,
    STATUS.ENTRY_FILLED,
    STATUS.ENTRY_FAILED,
    STATUS.ENTRY_CANCELLED,
    STATUS.ENTRY_REPLACED,
  ]),
  [STATUS.ENTRY_OPEN]: new Set([
    STATUS.ENTRY_FILLED,
    STATUS.ENTRY_FAILED,
    STATUS.ENTRY_CANCELLED,
    STATUS.ENTRY_REPLACED,
    STATUS.GUARD_FAILED,
  ]),
  [STATUS.ENTRY_REPLACED]: new Set([
    STATUS.ENTRY_OPEN,
    STATUS.ENTRY_FILLED,
    STATUS.ENTRY_FAILED,
    STATUS.ENTRY_CANCELLED,
    STATUS.GUARD_FAILED,
  ]),
  [STATUS.ENTRY_FILLED]: new Set([STATUS.SL_PLACED, STATUS.SL_OPEN, STATUS.SL_CONFIRMED, STATUS.LIVE, STATUS.EXITED_TARGET, STATUS.EXITED_SL, STATUS.GUARD_FAILED, STATUS.CLOSED]),
  [STATUS.LIVE]: new Set([STATUS.SL_OPEN, STATUS.SL_CONFIRMED, STATUS.EXIT_PLACED, STATUS.EXIT_OPEN, STATUS.EXIT_PARTIAL, STATUS.EXIT_FILLED, STATUS.PANIC_EXIT_PLACED, STATUS.PANIC_EXIT_CONFIRMED, STATUS.EXITED_TARGET, STATUS.EXITED_SL, STATUS.GUARD_FAILED, STATUS.CLOSED]),
  [STATUS.SL_PLACED]: new Set([
    STATUS.SL_OPEN,
    STATUS.SL_CONFIRMED,
    STATUS.LIVE,
    STATUS.PANIC_EXIT_PLACED,
    STATUS.GUARD_FAILED,
    STATUS.CLOSED,
  ]),
  [STATUS.SL_OPEN]: new Set([STATUS.SL_CONFIRMED, STATUS.PANIC_EXIT_PLACED, STATUS.GUARD_FAILED, STATUS.CLOSED]),
  [STATUS.SL_CONFIRMED]: new Set([
    STATUS.LIVE,
    STATUS.EXIT_PLACED,
    STATUS.EXIT_OPEN,
    STATUS.EXIT_PARTIAL,
    STATUS.EXIT_FILLED,
    STATUS.EXITED_TARGET,
    STATUS.EXITED_SL,
    STATUS.PANIC_EXIT_CONFIRMED,
    STATUS.PANIC_EXIT_PLACED,
    STATUS.GUARD_FAILED,
    STATUS.CLOSED,
  ]),
  [STATUS.EXIT_PLACED]: new Set([STATUS.EXIT_OPEN, STATUS.EXIT_PARTIAL, STATUS.EXIT_FILLED, STATUS.PANIC_EXIT_PLACED, STATUS.EXITED_TARGET, STATUS.EXITED_SL, STATUS.CLOSED]),
  [STATUS.EXIT_OPEN]: new Set([STATUS.EXIT_PARTIAL, STATUS.EXIT_FILLED, STATUS.PANIC_EXIT_PLACED, STATUS.EXITED_TARGET, STATUS.EXITED_SL, STATUS.CLOSED]),
  [STATUS.EXIT_PARTIAL]: new Set([STATUS.EXIT_FILLED, STATUS.PANIC_EXIT_PLACED, STATUS.EXITED_TARGET, STATUS.EXITED_SL, STATUS.CLOSED]),
  [STATUS.EXIT_FILLED]: new Set([STATUS.CLOSED]),
  [STATUS.PANIC_EXIT_PLACED]: new Set([STATUS.PANIC_EXIT_CONFIRMED, STATUS.GUARD_FAILED, STATUS.CLOSED]),
  [STATUS.PANIC_EXIT_CONFIRMED]: new Set([STATUS.CLOSED]),
  [STATUS.RECOVERY_REHYDRATED]: new Set([STATUS.SL_PLACED, STATUS.SL_OPEN, STATUS.SL_CONFIRMED, STATUS.LIVE, STATUS.GUARD_FAILED, STATUS.CLOSED]),
  [STATUS.EXITED_TARGET]: new Set([STATUS.CLOSED]),
  [STATUS.EXITED_SL]: new Set([STATUS.CLOSED]),
  [STATUS.ENTRY_FAILED]: new Set([STATUS.CLOSED]),
  [STATUS.ENTRY_CANCELLED]: new Set([STATUS.CLOSED]),
  [STATUS.GUARD_FAILED]: new Set([
    STATUS.PANIC_EXIT_PLACED,
    STATUS.PANIC_EXIT_CONFIRMED,
    STATUS.CLOSED,
  ]),
  [STATUS.CLOSED]: new Set([STATUS.CLOSED]),
};

const TERMINAL = new Set([
  STATUS.CLOSED,
  STATUS.EXITED_TARGET,
  STATUS.EXITED_SL,
  STATUS.EXIT_FILLED,
  STATUS.PANIC_EXIT_CONFIRMED,
  STATUS.ENTRY_FAILED,
  STATUS.ENTRY_CANCELLED,
]);

const KNOWN_STATUSES = new Set(Object.values(STATUS));

function normalizeTradeStatus(status) {
  const s = String(status || "").trim().toUpperCase();
  return STATUS[s] || s;
}

function canTransition(fromStatus, toStatus) {
  const from = normalizeTradeStatus(fromStatus);
  const to = normalizeTradeStatus(toStatus);
  if (!to) return { ok: false, reason: "TO_EMPTY" };
  if (!KNOWN_STATUSES.has(to)) return { ok: false, reason: "UNKNOWN_TO" };
  if (!from) return { ok: false, reason: "FROM_EMPTY" };
  if (!KNOWN_STATUSES.has(from)) return { ok: false, reason: "UNKNOWN_FROM" };
  if (from === to) return { ok: true, reason: "NOOP" };
  if (TERMINAL.has(from) && to !== STATUS.CLOSED) {
    return { ok: false, reason: "FROM_TERMINAL" };
  }
  const allowed = ALLOWED_TRANSITIONS[from];
  if (!allowed) return { ok: false, reason: "UNKNOWN_FROM" };
  if (allowed.has(to)) return { ok: true, reason: "ALLOWED" };
  return { ok: false, reason: "INVALID_TRANSITION" };
}

module.exports = {
  STATUS,
  KNOWN_STATUSES,
  normalizeTradeStatus,
  canTransition,
};
